Actualize actions

diff --git a/.github/workflows/win-release.yml b/.github/workflows/win-release.yml
--- a/.github/workflows/win-release.yml
+++ b/.github/workflows/win-release.yml
@@ -41,8 +41,8 @@ jobs:
       SDK: "10.0.18362.0"
       VC: "call vcvars32.bat && cd Libraries"
       GIT: "https://github.com"
-      QT: "5_12_8"
-      QT_VER: "5.12.8"
+      QT: "5_15_2"
+      QT_VER: "5.15.2"
       OPENSSL_VER: "1_1_1"
       ONLY_CACHE: "false"
       MANUAL_CACHING: "2"
@@ -50,6 +50,10 @@ jobs:
       REPO_NAME: "kotatogram-desktop"
       REPO_CHECKOUT_NAME: "kotatogram/kotatogram-desktop"
       AUTO_CACHING: "1"
+
+    defaults:
+      run:
+        shell: cmd
 
     steps:
       - name: Allow long file paths.
@@ -82,38 +86,35 @@ jobs:
           PACKER_PRIVATE_BETA_KEY: ${{ secrets.PACKER_PRIVATE_BETA_KEY }}
         run: python buildscripts/scripts/updater_keys.py
 
-      - name: Set up environment variables.
-        shell: cmd
+      - name: Set up environment paths.
+        shell: bash
         run: |
-          echo ::add-path::C:\Strawberry\perl\bin\
-          echo ::add-path::"%programfiles%\NASM"
+          echo "C:\\Strawberry\\perl\\bin\\" >> $GITHUB_PATH
+          echo "C:\\Program Files\\NASM\\" >> $GITHUB_PATH
+          echo "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\" >> $GITHUB_PATH
 
-          C:
-          cd "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\"
-          echo ::add-path::%cd%
+          mkdir Libraries && cd Libraries
+          echo "Convert unix path to win path."
+          p=`pwd | sed 's#^/[d]#d:#g' |sed 's#/#\\\\#g'`
+          echo "LibrariesPath=$p" >> $GITHUB_ENV
 
+      - name: Save msbuild version.
+        run: |
           call vcvars32.bat
-          D:
-          cd %GITHUB_WORKSPACE%
           msbuild -version > CACHE_KEY.txt
-          echo %MANUAL_CACHING% >> CACHE_KEY.txt
-
-          mkdir Libraries
-          cd Libraries
-          echo ::set-env name=LibrariesPath::%cd%
 
       - name: Generate cache key.
         shell: bash
         run: |
+          echo $MANUAL_CACHING >> CACHE_KEY.txt
           if [ "$AUTO_CACHING" == "1" ]; then
             thisFile=buildscripts/.github/workflows/win-release.yml
             echo `md5sum $thisFile | awk '{ print $1 }'` >> CACHE_KEY.txt
           fi
-          echo ::set-env name=CACHE_KEY::`md5sum CACHE_KEY.txt | awk '{ print $1 }'`
+          echo "CACHE_KEY=`md5sum CACHE_KEY.txt | awk '{ print $1 }'`" >> $GITHUB_ENV
 
       - name: Choco installs.
-        run: |
-          choco install --no-progress -y nasm yasm jom ninja
+        run: choco install --no-progress -y nasm yasm jom ninja
 
       - name: Patches.
         shell: bash
@@ -125,8 +126,19 @@ jobs:
           cd Patches
           eval $checkoutCommit
 
+      - name: Find any version of Python 2.
+        shell: bash
+        run: |
+          echo "Find any version of Python 2."
+          p=`ls /c/hostedtoolcache/windows/python | grep 2 | tail -1`
+          if [ -z "$p" ]; then
+            echo "Python 2 is not found."
+            exit 1
+          fi
+          echo "PY2=C:\\hostedtoolcache\\windows\\Python\\$p\\x64" >> $GITHUB_ENV
+          echo "Found $p."
+
       - name: LZMA.
-        shell: cmd
         run: |
           %VC%
 
@@ -144,7 +156,6 @@ jobs:
           key: ${{ runner.OS }}-${{ env.CACHE_KEY }}-${{ env.OPENSSL_VER }}
       - name: OpenSSL.
         if: steps.cache-openssl.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
 
@@ -170,7 +181,6 @@ jobs:
           rmdir /S /Q .git
 
       - name: Zlib.
-        shell: cmd
         run: |
           %VC%
 
@@ -180,6 +190,20 @@ jobs:
           cd contrib\vstudio\vc14
           msbuild -m zlibstat.vcxproj /property:Configuration=ReleaseWithoutAsm
 
+      - name: MozJPEG.
+        shell: cmd
+        run: |
+          %VC%
+
+          git clone -b v4.0.1-rc2 %GIT%/mozilla/mozjpeg.git
+          cd mozjpeg
+          cmake . ^
+          -G "Visual Studio 16 2019" ^
+          -A Win32 ^
+          -DWITH_JPEG8=ON ^
+          -DPNG_SUPPORTED=OFF
+          cmake --build . --config Release
+
       - name: OpenAL Soft cache.
         id: cache-openal
         if: ${{ needs.check.outputs.cache }}
@@ -188,20 +212,18 @@ jobs:
           path: ${{ env.LibrariesPath }}/openal-soft
           key: ${{ runner.OS }}-openal-soft-${{ env.CACHE_KEY }}
       - name: OpenAL Soft.
-        shell: cmd
         if: steps.cache-openal.outputs.cache-hit != 'true'
         run: |
           %VC%
 
-          git clone %GIT%/telegramdesktop/openal-soft.git
-          cd openal-soft
-          git checkout fix_capture
-          cd build
-          cmake ^
+          git clone -b openal-soft-1.21.0 --depth=1 %GIT%/kcat/openal-soft.git
+          cd openal-soft\build
+          cmake .. ^
           -G "Visual Studio 16 2019" ^
           -A Win32 ^
           -D LIBTYPE:STRING=STATIC ^
-          -D FORCE_STATIC_VCRT:STRING=ON ..
+          -D FORCE_STATIC_VCRT=ON ^
+          -D ALSOFT_BACKEND_DSOUND=OFF
 
           msbuild -m OpenAL.vcxproj /property:Configuration=Release
 
@@ -214,7 +236,6 @@ jobs:
           key: ${{ runner.OS }}-opus-${{ env.CACHE_KEY }}
       - name: Opus.
         if: steps.cache-opus.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
 
@@ -233,30 +254,28 @@ jobs:
           key: ${{ runner.OS }}-ffmpeg-${{ env.CACHE_KEY }}-2-${{ hashFiles('**/build_ffmpeg_win.sh') }}
       - name: FFmpeg.
         if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
           choco install --no-progress -y msys2
 
           git clone %GIT%/FFmpeg/FFmpeg.git ffmpeg
           cd ffmpeg
-          git checkout release/3.4
+          git checkout release/4.2
           set CHERE_INVOKING=enabled_from_arguments
           set MSYS2_PATH_TYPE=inherit
-          call c:\tools\msys64\usr\bin\bash --login ../../%REPO_NAME%/Telegram/Patches/build_ffmpeg_win.sh
+          call c:\tools\msys64\usr\bin\bash --login ../patches/build_ffmpeg_win.sh
 
           rmdir /S /Q .git
 
-      - name: Qt 5.12.8 cache.
+      - name: Qt 5.15.2 cache.
         id: cache-qt
         if: ${{ needs.check.outputs.cache }}
         uses: actions/cache@v2
         with:
           path: ${{ env.LibrariesPath }}/Qt-${{ env.QT_VER }}
-          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}-${{ hashFiles('**/qtbase_5_12_8/*') }}
-      - name: Configure Qt 5.12.8.
+          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}-${{ hashFiles('**/qtbase_5_15_2/*') }}
+      - name: Configure Qt 5.15.2.
         if: steps.cache-qt.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
 
@@ -287,10 +306,12 @@ jobs:
           -mp ^
           -nomake examples ^
           -nomake tests ^
-          -platform win32-msvc
-      - name: Qt 5.12.8 build.
+          -platform win32-msvc ^
+          -I "%LibrariesPath%\mozjpeg" ^
+          LIBJPEG_LIBS_DEBUG="%LibrariesPath%\mozjpeg\Debug\jpeg-static.lib" ^
+          LIBJPEG_LIBS_RELEASE="%LibrariesPath%\mozjpeg\Release\jpeg-static.lib"
+      - name: Qt 5.15.2 build.
         if: steps.cache-qt.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
           cd qt_%QT%
@@ -309,32 +330,16 @@ jobs:
           key: ${{ runner.OS }}-webrtc-${{ env.CACHE_KEY }}
       - name: WebRTC.
         if: steps.cache-webrtc.outputs.cache-hit != 'true'
-        shell: cmd
         run: |
           %VC%
 
-          :: Qt libjpeg.
-          mkdir qt_%QT%
-          cd qt_%QT%
-          git clone -b %QT_VER% https://github.com/qt/qtbase
-
-          move qtbase\src\3rdparty\libjpeg ..
-          cd ..
-          dir
-          rmdir /S /Q qt_%QT%
-          mkdir qt_%QT%\qtbase\src\3rdparty\
-          move libjpeg qt_%QT%\qtbase\src\3rdparty\
-
-          :: WebRTC.
-          cd %LibrariesPath%
-
-          git clone %GIT%/desktop-app/tg_owt.git
+          git clone --recursive %GIT%/desktop-app/tg_owt.git
           mkdir tg_owt\out\Release
           cd tg_owt\out\Release
           cmake -G Ninja ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DTG_OWT_SPECIAL_TARGET=win ^
-          -DTG_OWT_LIBJPEG_INCLUDE_PATH=%cd%/../../../qt_%QT%/qtbase/src/3rdparty/libjpeg ^
+          -DTG_OWT_LIBJPEG_INCLUDE_PATH=%cd%/../../../mozjpeg ^
           -DTG_OWT_OPENSSL_INCLUDE_PATH=%cd%/../../../openssl_%OPENSSL_VER%/include ^
           -DTG_OWT_OPUS_INCLUDE_PATH=%cd%/../../../opus/include ^
           -DTG_OWT_FFMPEG_INCLUDE_PATH=%cd%/../../../ffmpeg ^
@@ -349,12 +354,8 @@ jobs:
           mkdir out\Release
           move tg_owt.lib out\Release\tg_owt.lib
 
-          cd %LibrariesPath%
-          rmdir /S /Q qt_%QT%
-
       - name: Kotatogram Desktop build.
         if: env.ONLY_CACHE == 'false'
-        shell: cmd
         env:
           API_ID: ${{ secrets.API_ID }}
           API_HASH: ${{ secrets.API_HASH }}
@@ -387,7 +388,7 @@ jobs:
           cd $REPO_NAME
 
           artifact_name=${{ env.VERSION_STR }}.zip
-          echo ::set-env name=ARTIFACT_NAME::$artifact_name
+          echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
 
           mkdir -p artifact/Kotatogram
           mv build/bin/Kotatogram.exe artifact/Kotatogram
